CREATE TABLE HPTL_EMPRESA (
ID_EMPRESA NUMBER(5) NOT NULL,
NOMBRE_EMPRESA VARCHAR2(40) NOT NULL,
DIRECCIONES_ID NUMBER(9) NOT NULL,
CONSTRAINT PK_HPTL_EMPRESA PRIMARY KEY (ID_EMPRESA),
CONSTRAINT PK_HPTL_DIR_HPTL_EMP_FK FOREIGN KEY(DIRECCIONES_ID) REFERENCES HPTL_DIRECCIONES(ID)
);

CREATE TABLE HPTL_EMPRESA_CLINICA (
ID_EMPRESA_CLINICA NUMBER(5) NOT NULL, 
CLINICA_ID NUMBER(9) NOT NULL,
ID_EMPRESA NUMBER(5) NOT NULL, 
CONSTRAINT PK_HPTL_EMP_CLI PRIMARY KEY (ID_EMPRESA_CLINICA),
CONSTRAINT PK_HPTL_CLI_HPTL_EMP_CLI_FK FOREIGN KEY(CLINICA_ID) REFERENCES HPTL_CLINICAS(ID),
CONSTRAINT PK_HPTL_EMP_HPTL_EMP_CLI_FK FOREIGN KEY(ID_EMPRESA) REFERENCES HPTL_EMPRESA(ID_EMPRESA)
);

CREATE TABLE HPTL_EMPO_EMP_CLI (
ID_EMPO_EMP_CLI NUMBER(5) NOT NULL, 
ID_EMPRESA_CLINICA NUMBER(5) NOT NULL, 
EMPLEADOS_PUESTOS_ID NUMBER(9) NOT NULL,
CONSTRAINT PK_HPTL_EMPO_EMP_CLI PRIMARY KEY (ID_EMPO_EMP_CLI),
CONSTRAINT PK_HPTL_EMP_CLI_HPTL_E_E_C_FK FOREIGN KEY(ID_EMPRESA_CLINICA) REFERENCES HPTL_EMPRESA_CLINICA(ID_EMPRESA_CLINICA),
CONSTRAINT PK_HPTL_EMPO_PUE_HPTL_E_E_C_FK FOREIGN KEY(EMPLEADOS_PUESTOS_ID) REFERENCES HPTL_EMPLEADOS_PUESTOS(ID)
);

CREATE TABLE HPTL_TURNO (
ID_TURNO NUMBER(5) NOT NULL, 
DESCRIPCION_TURNO VARCHAR2(30) NOT NULL, 
CONSTRAINT PK_HPTL_TURNO PRIMARY KEY (ID_TURNO)
);

CREATE TABLE HPTL_TURNO_EMPLEADO (
ID_TURNO_EMPLEADO NUMBER(5) NOT NULL, 
EMPLEADOS_PUESTOS_ID NUMBER(9) NOT NULL, 
ID_TURNO NUMBER(5) NOT NULL, 
HORARIOS_ID NUMBER(9) NOT NULL, 
FECHA_INICIO_TURNO DATE NOT NULL, 
FECHA_FIN_TURNO DATE NOT NULL,
CREADOPOR VARCHAR2(30) NOT NULL,
FECHACREACION DATE NOT NULL, 
CONSTRAINT PK_HPTL_TURNO_EMPLEADO PRIMARY KEY (ID_TURNO_EMPLEADO),
CONSTRAINT PK_HPTL_EMPO_PUE_HPTL_T_E_FK FOREIGN KEY(EMPLEADOS_PUESTOS_ID) REFERENCES HPTL_EMPLEADOS_PUESTOS(ID),
CONSTRAINT PK_HPTL_TURNO_HPTL_T_E_FK FOREIGN KEY(ID_TURNO) REFERENCES HPTL_TURNO(ID_TURNO),
CONSTRAINT PK_HPTL_HORARI_HPTL_T_E_FK FOREIGN KEY(HORARIOS_ID) REFERENCES HPTL_HORARIOS(ID)
);

CREATE TABLE HPTL_DIRECCION_EMPLEADO (
ID_DIRECCION_EMPLEADO NUMBER(5) NOT NULL, 
EMPLEADOS_ID NUMBER(9) NOT NULL,
DIRECCIONES_ID NUMBER(9) NOT NULL,
CONSTRAINT PK_HPTL_DIR_EMP PRIMARY KEY (ID_DIRECCION_EMPLEADO),
CONSTRAINT PK_HPTL_EMPO_HPTL_DIR_EMPO_FK FOREIGN KEY(EMPLEADOS_ID) REFERENCES HPTL_EMPLEADOS(ID),
CONSTRAINT PK_HPTL_DIR_HPTL_DIR_EMPO_FK FOREIGN KEY(DIRECCIONES_ID) REFERENCES HPTL_DIRECCIONES(ID)
);

CREATE TABLE HPTL_MOV_ADMIN (
ID_MOV_ADMIN NUMBER(5) NOT NULL,
DESCRIPCION_MOV VARCHAR2(30) NOT NULL, 
CONSTRAINT PK_HPTL_MOV_ADMIN PRIMARY KEY (ID_MOV_ADMIN),
);

CREATE TABLE HPTL_DET_MOV_ADMIN (
ID_DET_MOV_ADMIN NUMBER(5) NOT NULL, 
ID_MOV_ADMIN NUMBER(5) NOT NULL, 
FECHA_INICIO_MOV DATE NOT NULL, 
FECHA_FIN_MOV DATE NOT NULL, 
PUESTO_ANTERIOR NUMBER(9),
PUESTO_NUEVO NUMBER(9),
EMPLEADOS_ID NUMBER(9) NOT NULL, 
SUELDO_BASE NUMBER(9),
SUELDO_BONIFICACION NUMBER(9),
SUELDO_COMISION NUMBER(9),
CREADOPOR VARCHAR2(30) NOT NULL, 
FECHACREACION DATE NOT NULL,
CONSTRAINT PK_HPTL_DET_MOV_ADMIN PRIMARY KEY (ID_DET_MOV_ADMIN),
CONSTRAINT PK_HPTL_MO_AD_HPTL_D_M_A_FK FOREIGN KEY(ID_MOV_ADMIN) REFERENCES HPTL_MOV_ADMIN(ID_MOV_ADMIN),
CONSTRAINT PK_HPTL_EMPO_HPTL_D_M_A_FK FOREIGN KEY(EMPLEADOS_ID) REFERENCES HPTL_EMPLEADOS(ID)
);

CREATE TABLE HPTL_BITACORA (
ID_BITACORA NUMBER (50) NOT NULL,
TABLA_AFECTADA VARCHAR2(50) NOT NULL,
CAMPO_AFECTADO VARCHAR2(35),
VALOR_ANTERIOR VARCHAR2(35),
VALOR_NUEVO VARCHAR2(35),
FECHA_BITACORA DATE NOT NULL,
USER_BITACORA VARHCAR2(30),
CONSTRAINT PK_HPTL_BITACORA PRIMARY KEY (ID_BITACORA)
);


--SECUENCIAS PARA IDs (Tablas del Grupo#10)

CREATE SEQUENCE SEQ_EMPRESA
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999999;

CREATE SEQUENCE SEQ_EMPRESA_CLINICA
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999999;

CREATE SEQUENCE SEQ_EMPO_EMP_CLI
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999999;

CREATE SEQUENCE SEQ_TURNO
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999999;

CREATE SEQUENCE SEQ_TURNO_EMPLEADO
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999999;

CREATE SEQUENCE SEQ_DIRECCION_EMPLEADO
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999999;

CREATE SEQUENCE SEQ_MOV_ADMIN
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999999;

CREATE SEQUENCE SEQ_DET_MOV_ADMIN
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999999;

CREATE SEQUENCE SEQ_BITACORA
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999999;