/*VISTA LABORATORIOS PARA CONSULTAS FRONT-END*/
CREATE VIEW HOSPITAL.LAB_VW_LABS 
AS
SELECT  LC.IDLABOCABE, LC.DSLABOCABE,LC.IDLABOTIPO,LT.DSLABOTIPO,
TO_DATE(LC.FECHALABOCABE, 'DD/MM/YYYY') as FECHALABOCABE,LC.ACTIVO
FROM HOSPITAL.LABORATORIOS_CABE LC, HOSPITAL.LABORATORIOS_TIPO LT
WHERE  LC.IDLABOTIPO = LT.IDLABOTIPO
ORDER BY LC.DSLABOCABE ASC;
--SELECT * FROM LAB_VW_LABS;

/*VISTA DETALLE DE LABORATORIOS PARA CONSULTAS FRONT-END*/
CREATE VIEW HOSPITAL.LAB_VW_LABSDETAREQUI 
AS
SELECT LD.IDLABODETA,LD.IDLABOCABE,LD.IDLABOREQUI,LC.DSLABOCABE,LR.DSLABOREQUI 
FROM HOSPITAL.LABORATORIOS_DETA LD,HOSPITAL.LABORATORIOS_CABE LC,HOSPITAL.LABORATORIOS_REQUISITO LR
WHERE LD.IDLABOCABE = LC.IDLABOCABE
AND LD.IDLABOREQUI = LR.IDLABOREQUI
ORDER BY LC.DSLABOCABE , LR.DSLABOREQUI ASC;

/*VISTA DE PACIENTES - PERSONAS FRONT-END*/
CREATE VIEW HOSPITAL.LAB_VW_PER_PAC
AS
SELECT PA.ID AS IDPACIENTE,PE.PRIMER_NOMBRE||' '||PE.PRIMER_APELLIDO AS DSPACIENTE
FROM HOSPITAL.HPTL_PACIENTES PA
INNER JOIN HPTL_PERSONAS PE
ON PA.PERSONAS_ID = PE.ID
ORDER BY DSPACIENTE ASC;

/*VISTA ORDEN DE LABORATORIOS PARA CONSULTAS FRONT-END*/
CREATE VIEW HOSPITAL.LAB_VW_LABORDPAC
AS
SELECT OL.IDLABOORDEN,PA.CODIGO_PACIENTE,TO_DATE(OL.FECHAORDEN, 'DD/MM/YYYY') AS FECHAORDEN,OL.ESTADO
FROM HOSPITAL.LABORATORIOS_ORDEN OL,HOSPITAL.HPTL_PACIENTES PA
WHERE OL.IDPACIENTE = PA.ID
ORDER BY OL.IDLABOORDEN ASC;
