-- Generado por Oracle SQL Developer Data Modeler 4.1.3.901
--   en:        2016-05-23 22:00:13 CST
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE TABLE AREAS
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE AREAS ADD CONSTRAINT AREA_PK PRIMARY KEY ( ID ) ;


CREATE TABLE CITA
  (
    ID                   NUMBER NOT NULL ,
    FECHA_CITA           DATE NOT NULL ,
    HORA_CITA            TIMESTAMP NOT NULL ,
    TIPO_CITA_ID         NUMBER NOT NULL ,
    PACIENTE_ID          NUMBER NOT NULL ,
    DOCTORES_ID          NUMBER NOT NULL ,
    ESTADO_CITA_ID       NUMBER NOT NULL ,
    CONSULTORIO_ID       NUMBER NOT NULL ,
    HABITACION_ID        NUMBER NOT NULL ,
    QUIROFANO_ID         NUMBER NOT NULL ,
    ESTUDIOS_ID          NUMBER NOT NULL ,
    RESPONSABLE_TURNO_ID NUMBER NOT NULL
  ) ;
ALTER TABLE CITA ADD CONSTRAINT CITA_PK PRIMARY KEY ( ID ) ;


CREATE TABLE CONSULTORIO
  (
    ID         NUMBER NOT NULL ,
    DESCIPRION VARCHAR2 (20) NOT NULL ,
    NIVELES_ID NUMBER NOT NULL
  ) ;
ALTER TABLE CONSULTORIO ADD CONSTRAINT CONSULTORIO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE DEPARTAMENTO
  ( ID NUMBER NOT NULL , DESCRIPCION VARCHAR2 (20)
  ) ;
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE DETALLE_EXPEDIENTE
  (
    ID             NUMBER NOT NULL ,
    EXPEDIENTE_ID  NUMBER NOT NULL ,
    DIAGNOSTICO_ID NUMBER NOT NULL
  ) ;
ALTER TABLE DETALLE_EXPEDIENTE ADD CONSTRAINT DETALLE_EXPEDIENTE_PK PRIMARY KEY ( ID ) ;


CREATE TABLE DIAGNOSTICO
  (
    ID                  NUMBER NOT NULL ,
    ENFERMEDAD_ID       NUMBER NOT NULL ,
    NIVEL_ENFERMEDAD_ID NUMBER NOT NULL ,
    ESTUDIOS_ID         NUMBER NOT NULL
  ) ;
ALTER TABLE DIAGNOSTICO ADD CONSTRAINT DIAGNOSTICO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE DIRECCION
  (
    ID                NUMBER NOT NULL ,
    LOTE              VARCHAR2 (10) NOT NULL ,
    COLONIA_O_SIMILAR VARCHAR2 (30) ,
    CALLE_AVENIDA     VARCHAR2 (30) ,
    ZONA              VARCHAR2 (10) ,
    PAIS_ID           NUMBER NOT NULL ,
    MUNICIPIO_ID      NUMBER NOT NULL ,
    DEPARTAMENTO_ID   NUMBER NOT NULL
  ) ;
ALTER TABLE DIRECCION ADD CONSTRAINT DIRECCION_PK PRIMARY KEY ( ID ) ;


CREATE TABLE DIRECCION_PERSONA
  (
    ID           NUMBER NOT NULL ,
    PERSONA_ID   NUMBER NOT NULL ,
    DIRECCION_ID NUMBER NOT NULL
  ) ;
ALTER TABLE DIRECCION_PERSONA ADD CONSTRAINT DIRECCION_PERSONA_PK PRIMARY KEY ( ID ) ;


CREATE TABLE DOCTORES
  ( ID NUMBER NOT NULL , EMPLEADO_ID NUMBER NOT NULL
  ) ;
ALTER TABLE DOCTORES ADD CONSTRAINT DOCTORES_PK PRIMARY KEY ( ID ) ;


CREATE TABLE DOCTOR_ESPECIALIDAD
  (
    ID                NUMBER NOT NULL ,
    DOCTORES_ID       NUMBER NOT NULL ,
    ESPECIALIDADES_ID NUMBER NOT NULL
  ) ;
ALTER TABLE DOCTOR_ESPECIALIDAD ADD CONSTRAINT DOCTOR_ESPECIALIDAD_PK PRIMARY KEY ( ID ) ;


CREATE TABLE DOCUMENTO
  (
    ID                NUMBER NOT NULL ,
    DOCUMENTO         VARCHAR2 (20) NOT NULL ,
    TIPO_DOCUMENTO_ID NUMBER NOT NULL
  ) ;
ALTER TABLE DOCUMENTO ADD CONSTRAINT DOCUMENTO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE EDIFICIO
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (20) NOT NULL ,
    NIVELES     NUMBER NOT NULL
  ) ;
ALTER TABLE EDIFICIO ADD CONSTRAINT EDIFICIO_PK PRIMARY KEY ( ID, DESCRIPCION ) ;


CREATE TABLE EMERGENCIA
  (
    ID                   NUMBER NOT NULL ,
    TIPO_EMERGENCIA_ID   NUMBER NOT NULL ,
    PACIENTE_ID          NUMBER NOT NULL ,
    FECHA_EMERGENCIA     DATE NOT NULL ,
    HORA_EMERGENCIA      TIMESTAMP NOT NULL ,
    RESPONSABLE_TURNO_ID NUMBER NOT NULL ,
    HABITACION_ID        NUMBER NOT NULL
  ) ;
ALTER TABLE EMERGENCIA ADD CONSTRAINT EMERGENCIA_PK PRIMARY KEY ( ID ) ;


CREATE TABLE EMPLEADO
  ( ID NUMBER NOT NULL , PERSONA_ID NUMBER NOT NULL
  ) ;
ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE ENFERMEDAD
  (
    ID                 NUMBER NOT NULL ,
    DESCRIPCION        VARCHAR2 (40) NOT NULL ,
    TIPO_ENFERMEDAD_ID NUMBER NOT NULL
  ) ;
ALTER TABLE ENFERMEDAD ADD CONSTRAINT ENFERMEDAD_PK PRIMARY KEY ( ID ) ;


CREATE TABLE ESPECIALIDADES
  (
    ID               NUMBER NOT NULL ,
    DESCRIPCION      VARCHAR2 (20) NOT NULL ,
    SUB_ESPECIALIDAD VARCHAR2 (20)
  ) ;
ALTER TABLE ESPECIALIDADES ADD CONSTRAINT ESPECIALIDADES_PK PRIMARY KEY ( ID ) ;


CREATE TABLE ESTADO_CITA
  (
    ID     NUMBER NOT NULL ,
    ESTADO VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE ESTADO_CITA ADD CONSTRAINT ESTADO_CITA_PK PRIMARY KEY ( ID ) ;


CREATE TABLE ESTATUS_HABITACION
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE ESTATUS_HABITACION ADD CONSTRAINT ESTATUS_HABITACION_PK PRIMARY KEY ( ID ) ;


CREATE TABLE ESTATUS_QUIROFANO
  (
    ID     NUMBER NOT NULL ,
    STATUS VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE ESTATUS_QUIROFANO ADD CONSTRAINT ESTATUS_QUIROFANO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE ESTUDIOS
  (
    ID          NUMBER NOT NULL ,
    EXAMENES_ID NUMBER NOT NULL ,
    RESULTADOS  VARCHAR2 (20)
  ) ;
ALTER TABLE ESTUDIOS ADD CONSTRAINT ESTUDIOS_PK PRIMARY KEY ( ID ) ;


CREATE TABLE ETAPAS_TRATAMIENTO
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE ETAPAS_TRATAMIENTO ADD CONSTRAINT ETAPAS_TRATAMIENTO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE EXAMENES
  (
    ID               NUMBER NOT NULL ,
    TIPO_ESTUDIOS_ID NUMBER NOT NULL
  ) ;
ALTER TABLE EXAMENES ADD CONSTRAINT ESTUDIOS_PKv2 PRIMARY KEY ( ID ) ;


CREATE TABLE EXPEDIENTE
  (
    ID          NUMBER NOT NULL ,
    PACIENTE_ID NUMBER NOT NULL ,
    PESO        VARCHAR2 (20) NOT NULL ,
    ALTURA      VARCHAR2 (20) NOT NULL ,
    TIPO_SANGRE VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE EXPEDIENTE ADD CONSTRAINT EXPEDIENTE_PK PRIMARY KEY ( ID ) ;


CREATE TABLE HABITACION
  (
    ID                    NUMBER NOT NULL ,
    DESCRIPCION           VARCHAR2 (20) NOT NULL ,
    TIPO_HABITACION_ID    NUMBER NOT NULL ,
    NIVELES_ID            NUMBER NOT NULL ,
    ESTATUS_HABITACION_ID NUMBER NOT NULL
  ) ;
ALTER TABLE HABITACION ADD CONSTRAINT HABITACION_PK PRIMARY KEY ( ID ) ;


CREATE TABLE LABORATORIO
  (
    ID          NUMBER NOT NULL ,
    DESCIRPCION VARCHAR2 (30) NOT NULL ,
    NIVELES_ID  NUMBER NOT NULL
  ) ;
ALTER TABLE LABORATORIO ADD CONSTRAINT LABORATORIO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE MEDICINA
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE MEDICINA ADD CONSTRAINT MEDICINA_PK PRIMARY KEY ( ID ) ;


CREATE TABLE MUNICIPIO
  ( ID NUMBER NOT NULL , DESCRIPCION VARCHAR2 (20)
  ) ;
ALTER TABLE MUNICIPIO ADD CONSTRAINT MUNICIPIO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE NIVELES
  (
    ID                    NUMBER NOT NULL ,
    NUMERO                NUMBER NOT NULL ,
    ESPECIALIDAD          VARCHAR2 (30) NOT NULL ,
    CANTIDAD_CONSULTORIOS NUMBER NOT NULL ,
    CANTIDAD_HABITACIONES NUMBER NOT NULL ,
    EDIFICIO_ID           NUMBER NOT NULL ,
    EDIFICIO_DESCRIPCION  VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE NIVELES ADD CONSTRAINT NIVELES_PK PRIMARY KEY ( ID ) ;


CREATE TABLE NIVEL_ENFERMEDAD
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE NIVEL_ENFERMEDAD ADD CONSTRAINT NIVEL_ENFERMEDAD_PK PRIMARY KEY ( ID ) ;


CREATE TABLE PACIENTE
  ( ID NUMBER NOT NULL , PERSONA_ID NUMBER NOT NULL
  ) ;
ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_PK PRIMARY KEY ( ID ) ;


CREATE TABLE PAIS
  ( ID NUMBER NOT NULL , DESCRIPCION VARCHAR2 (30)
  ) ;
ALTER TABLE PAIS ADD CONSTRAINT PAIS_PK PRIMARY KEY ( ID ) ;


CREATE TABLE PERSONA
  (
    ID               NUMBER NOT NULL ,
    PRIMER_NOMBRE    VARCHAR2 (15) NOT NULL ,
    SEGUNDO_NOMBRE   VARCHAR2 (15) ,
    TERCER_NOMBRE    VARCHAR2 (15) ,
    PRIMER_APELLDO   VARCHAR2 (15) NOT NULL ,
    SEGUNDO_APELLIDO VARCHAR2 (15) ,
    APELLIDO_CASADO  VARCHAR2 (15) ,
    FECHA_NACIMIENTO DATE ,
    SEXO             VARCHAR2 (1) ,
    EMAIL            VARCHAR2 (30) ,
    DOCUMENTO_ID     NUMBER NOT NULL
  ) ;
ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_PK PRIMARY KEY ( ID ) ;


CREATE TABLE PROCESO_TRATAMIENTO
  (
    ID                      NUMBER NOT NULL ,
    ETAPAS_TRATAMIENTO_ID   NUMBER NOT NULL ,
    TRATAMIENTO_PACIENTE_ID NUMBER NOT NULL ,
    FECHA_INICIO            DATE NOT NULL
  ) ;
ALTER TABLE PROCESO_TRATAMIENTO ADD CONSTRAINT PROCESO_TRATAMIENTO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE PUESTO
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (30) NOT NULL ,
    EMPLEADO_ID NUMBER NOT NULL
  ) ;
ALTER TABLE PUESTO ADD CONSTRAINT PUESTO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE QUIROFANO
  (
    ID                   NUMBER NOT NULL ,
    DESCRIPCION          VARCHAR2 (20) NOT NULL ,
    ESTATUS_QUIROFANO_ID NUMBER NOT NULL ,
    NIVELES_ID           NUMBER NOT NULL
  ) ;
ALTER TABLE QUIROFANO ADD CONSTRAINT QUIROFANO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE RECETA
  (
    ID            NUMBER NOT NULL ,
    MEDICINA_ID   NUMBER NOT NULL ,
    TIEMPOCONSUMO VARCHAR2 (50) ,
    DETALLES      VARCHAR2 (30)
  ) ;
ALTER TABLE RECETA ADD CONSTRAINT RECETA_PK PRIMARY KEY ( ID ) ;


CREATE TABLE RESPONSABLE_TURNO
  (
    ID                     NUMBER NOT NULL ,
    AREAS_ID               NUMBER NOT NULL ,
    DOCTOR_ESPECIALIDAD_ID NUMBER NOT NULL ,
    TURNO_ID               NUMBER NOT NULL
  ) ;
ALTER TABLE RESPONSABLE_TURNO ADD CONSTRAINT RESPONSABLE_TURNO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TELEFONO_PERSONA
  (
    ID_TELEFONO_PERSONA NUMBER NOT NULL ,
    TELEFONO            NUMBER NOT NULL ,
    PERSONA_ID          NUMBER NOT NULL ,
    TIPO_TELEFONO_ID    NUMBER NOT NULL
  ) ;
ALTER TABLE TELEFONO_PERSONA ADD CONSTRAINT TELEFONO_PERSONA_PK PRIMARY KEY ( ID_TELEFONO_PERSONA ) ;


CREATE TABLE TIPO_CITA
  ( ID NUMBER NOT NULL , TIPO VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE TIPO_CITA ADD CONSTRAINT TIPO_CITA_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TIPO_DOCUMENTO
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE TIPO_DOCUMENTO ADD CONSTRAINT TIPO_DOCUMENTO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TIPO_EMERGENCIA
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE TIPO_EMERGENCIA ADD CONSTRAINT TIPO_EMERGENCIA_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TIPO_ENFERMEDAD
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (40) NOT NULL
  ) ;
ALTER TABLE TIPO_ENFERMEDAD ADD CONSTRAINT TIPO_ENFERMEDAD_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TIPO_EXAMENES
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE TIPO_EXAMENES ADD CONSTRAINT TIPO_ESTUDIOS_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TIPO_HABITACION
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE TIPO_HABITACION ADD CONSTRAINT TIPO_HABITACION_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TIPO_MEDICINA
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (20) NOT NULL ,
    MEDICINA_ID NUMBER NOT NULL
  ) ;
ALTER TABLE TIPO_MEDICINA ADD CONSTRAINT TIPO_MEDICINA_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TIPO_TELEFONO
  (
    ID            NUMBER NOT NULL ,
    TIPO_TELEFONO VARCHAR2 (25)
  ) ;
ALTER TABLE TIPO_TELEFONO ADD CONSTRAINT TIPO_TELEFONO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TIPO_TRATAMIENTO
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE TIPO_TRATAMIENTO ADD CONSTRAINT TIPO_TRATAMIENTO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TRATAMIENTOS
  (
    ID                  NUMBER NOT NULL ,
    DESCRIPCION         VARCHAR2 (20) NOT NULL ,
    TIPO_TRATAMIENTO_ID NUMBER NOT NULL
  ) ;
ALTER TABLE TRATAMIENTOS ADD CONSTRAINT TRATAMIENTOS_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TRATAMIENTO_PACIENTE
  (
    ID              NUMBER NOT NULL ,
    TRATAMIENTOS_ID NUMBER NOT NULL ,
    PACIENTE_ID     NUMBER NOT NULL
  ) ;
ALTER TABLE TRATAMIENTO_PACIENTE ADD CONSTRAINT TRATAMIENTO_PACIENTE_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TURNO
  (
    ID           NUMBER NOT NULL ,
    DESCRIPCION  VARCHAR2 (20) NOT NULL ,
    HORA_ENTRADA DATE NOT NULL ,
    HORA_SALIDA  DATE NOT NULL
  ) ;
ALTER TABLE TURNO ADD CONSTRAINT TURNO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TURNO_AREA
  (
    ID          NUMBER NOT NULL ,
    TURNO_ID    NUMBER NOT NULL ,
    AREAS_ID    NUMBER NOT NULL ,
    EMPLEADO_ID NUMBER NOT NULL
  ) ;
ALTER TABLE TURNO_AREA ADD CONSTRAINT TURNO_AREA_PK PRIMARY KEY ( ID ) ;


ALTER TABLE RESPONSABLE_TURNO ADD CONSTRAINT AREAS_FK FOREIGN KEY ( AREAS_ID ) REFERENCES AREAS ( ID ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_CONSULTORIO_FK FOREIGN KEY ( CONSULTORIO_ID ) REFERENCES CONSULTORIO ( ID ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_DOCTORES_FK FOREIGN KEY ( DOCTORES_ID ) REFERENCES DOCTORES ( ID ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_ESTADO_CITA_FK FOREIGN KEY ( ESTADO_CITA_ID ) REFERENCES ESTADO_CITA ( ID ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_ESTUDIOS_FK FOREIGN KEY ( ESTUDIOS_ID ) REFERENCES EXAMENES ( ID ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_HABITACION_FK FOREIGN KEY ( HABITACION_ID ) REFERENCES HABITACION ( ID ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_PACIENTE_FK FOREIGN KEY ( PACIENTE_ID ) REFERENCES PACIENTE ( ID ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_QUIROFANO_FK FOREIGN KEY ( QUIROFANO_ID ) REFERENCES QUIROFANO ( ID ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_RESPONSABLE_TURNO_FK FOREIGN KEY ( RESPONSABLE_TURNO_ID ) REFERENCES RESPONSABLE_TURNO ( ID ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_TIPO_CITA_FK FOREIGN KEY ( TIPO_CITA_ID ) REFERENCES TIPO_CITA ( ID ) ;

ALTER TABLE CONSULTORIO ADD CONSTRAINT CONSULTORIO_NIVELES_FK FOREIGN KEY ( NIVELES_ID ) REFERENCES NIVELES ( ID ) ;

ALTER TABLE DETALLE_EXPEDIENTE ADD CONSTRAINT DETALLE_DIAGNOSTICO_FK FOREIGN KEY ( DIAGNOSTICO_ID ) REFERENCES DIAGNOSTICO ( ID ) ;

ALTER TABLE DETALLE_EXPEDIENTE ADD CONSTRAINT DETALLE_EXPEDIENTE_FK FOREIGN KEY ( EXPEDIENTE_ID ) REFERENCES EXPEDIENTE ( ID ) ;

ALTER TABLE DIAGNOSTICO ADD CONSTRAINT DIAGNOSTICO_ENFERMEDAD_FK FOREIGN KEY ( ENFERMEDAD_ID ) REFERENCES ENFERMEDAD ( ID ) ;

ALTER TABLE DIAGNOSTICO ADD CONSTRAINT DIAGNOSTICO_ESTUDIOS_FK FOREIGN KEY ( ESTUDIOS_ID ) REFERENCES ESTUDIOS ( ID ) ;

ALTER TABLE DIAGNOSTICO ADD CONSTRAINT DIAGNOSTICO_NIVEL_FK FOREIGN KEY ( NIVEL_ENFERMEDAD_ID ) REFERENCES NIVEL_ENFERMEDAD ( ID ) ;

ALTER TABLE DIRECCION ADD CONSTRAINT DIRECCION_DEPARTAMENTO_FK FOREIGN KEY ( DEPARTAMENTO_ID ) REFERENCES DEPARTAMENTO ( ID ) ;

ALTER TABLE DIRECCION ADD CONSTRAINT DIRECCION_MUNICIPIO_FK FOREIGN KEY ( MUNICIPIO_ID ) REFERENCES MUNICIPIO ( ID ) ;

ALTER TABLE DIRECCION ADD CONSTRAINT DIRECCION_PAIS_FK FOREIGN KEY ( PAIS_ID ) REFERENCES PAIS ( ID ) ;

ALTER TABLE DIRECCION_PERSONA ADD CONSTRAINT DIRECCION_PERSONA_DIRECCION_FK FOREIGN KEY ( DIRECCION_ID ) REFERENCES DIRECCION ( ID ) ;

ALTER TABLE DIRECCION_PERSONA ADD CONSTRAINT DIRECCION_PERSONA_PERSONA_FK FOREIGN KEY ( PERSONA_ID ) REFERENCES PERSONA ( ID ) ;

ALTER TABLE DOCTORES ADD CONSTRAINT DOCTORES_EMPLEADO_FK FOREIGN KEY ( EMPLEADO_ID ) REFERENCES EMPLEADO ( ID ) ;

ALTER TABLE RESPONSABLE_TURNO ADD CONSTRAINT DOCTOR_ESPECIALIDAD_FK FOREIGN KEY ( DOCTOR_ESPECIALIDAD_ID ) REFERENCES DOCTOR_ESPECIALIDAD ( ID ) ;

ALTER TABLE DOCTOR_ESPECIALIDAD ADD CONSTRAINT DOCTOR_ESPECIALIDAD_FKv2 FOREIGN KEY ( DOCTORES_ID ) REFERENCES DOCTORES ( ID ) ;

ALTER TABLE DOCUMENTO ADD CONSTRAINT DOCUMENTO_TIPO_DOCUMENTO_FK FOREIGN KEY ( TIPO_DOCUMENTO_ID ) REFERENCES TIPO_DOCUMENTO ( ID ) ;

ALTER TABLE EMERGENCIA ADD CONSTRAINT EMERGENCIA_HABITACION_FK FOREIGN KEY ( HABITACION_ID ) REFERENCES HABITACION ( ID ) ;

ALTER TABLE EMERGENCIA ADD CONSTRAINT EMERGENCIA_PACIENTE_FK FOREIGN KEY ( PACIENTE_ID ) REFERENCES PACIENTE ( ID ) ;

ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_PERSONA_FK FOREIGN KEY ( PERSONA_ID ) REFERENCES PERSONA ( ID ) ;

ALTER TABLE ENFERMEDAD ADD CONSTRAINT ENFERMEDAD_TIPO_FK FOREIGN KEY ( TIPO_ENFERMEDAD_ID ) REFERENCES TIPO_ENFERMEDAD ( ID ) ;

ALTER TABLE DOCTOR_ESPECIALIDAD ADD CONSTRAINT ESPECIALIDADES_FK FOREIGN KEY ( ESPECIALIDADES_ID ) REFERENCES ESPECIALIDADES ( ID ) ;

ALTER TABLE HABITACION ADD CONSTRAINT ESTATUS_HABITACION_FK FOREIGN KEY ( ESTATUS_HABITACION_ID ) REFERENCES ESTATUS_HABITACION ( ID ) ;

ALTER TABLE QUIROFANO ADD CONSTRAINT ESTATUS_QUIROFANO_FK FOREIGN KEY ( ESTATUS_QUIROFANO_ID ) REFERENCES ESTATUS_QUIROFANO ( ID ) ;

ALTER TABLE ESTUDIOS ADD CONSTRAINT ESTUDIOS_EXAMENES_FK FOREIGN KEY ( EXAMENES_ID ) REFERENCES EXAMENES ( ID ) ;

ALTER TABLE EXAMENES ADD CONSTRAINT ESTUDIOS_TIPO_ESTUDIOS_FK FOREIGN KEY ( TIPO_ESTUDIOS_ID ) REFERENCES TIPO_EXAMENES ( ID ) ;

ALTER TABLE PROCESO_TRATAMIENTO ADD CONSTRAINT ETAPAS_TRATAMIENTO_FK FOREIGN KEY ( ETAPAS_TRATAMIENTO_ID ) REFERENCES ETAPAS_TRATAMIENTO ( ID ) ;

ALTER TABLE EXPEDIENTE ADD CONSTRAINT EXPEDIENTE_PACIENTE_FK FOREIGN KEY ( PACIENTE_ID ) REFERENCES PACIENTE ( ID ) ;

ALTER TABLE HABITACION ADD CONSTRAINT HABITACION_NIVELES_FK FOREIGN KEY ( NIVELES_ID ) REFERENCES NIVELES ( ID ) ;

ALTER TABLE LABORATORIO ADD CONSTRAINT LABORATORIO_NIVELES_FK FOREIGN KEY ( NIVELES_ID ) REFERENCES NIVELES ( ID ) ;

ALTER TABLE NIVELES ADD CONSTRAINT NIVELES_EDIFICIO_FK FOREIGN KEY ( EDIFICIO_ID, EDIFICIO_DESCRIPCION ) REFERENCES EDIFICIO ( ID, DESCRIPCION ) ;

ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_PERSONA_FK FOREIGN KEY ( PERSONA_ID ) REFERENCES PERSONA ( ID ) ;

ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_DOCUMENTO_FK FOREIGN KEY ( DOCUMENTO_ID ) REFERENCES DOCUMENTO ( ID ) ;

ALTER TABLE PROCESO_TRATAMIENTO ADD CONSTRAINT PROCESO_PACIENTE_FK FOREIGN KEY ( TRATAMIENTO_PACIENTE_ID ) REFERENCES TRATAMIENTO_PACIENTE ( ID ) ;

ALTER TABLE PUESTO ADD CONSTRAINT PUESTO_EMPLEADO_FK FOREIGN KEY ( EMPLEADO_ID ) REFERENCES EMPLEADO ( ID ) ;

ALTER TABLE QUIROFANO ADD CONSTRAINT QUIROFANO_NIVELES_FK FOREIGN KEY ( NIVELES_ID ) REFERENCES NIVELES ( ID ) ;

ALTER TABLE RECETA ADD CONSTRAINT RECETA_MEDICINA_FK FOREIGN KEY ( MEDICINA_ID ) REFERENCES MEDICINA ( ID ) ;

ALTER TABLE EMERGENCIA ADD CONSTRAINT RESPONSABLE_TURNO_FK FOREIGN KEY ( RESPONSABLE_TURNO_ID ) REFERENCES RESPONSABLE_TURNO ( ID ) ;

ALTER TABLE TELEFONO_PERSONA ADD CONSTRAINT TELEFONO_PERSONA_FK FOREIGN KEY ( PERSONA_ID ) REFERENCES PERSONA ( ID ) ;

ALTER TABLE EMERGENCIA ADD CONSTRAINT TIPO_EMERGENCIA_FK FOREIGN KEY ( TIPO_EMERGENCIA_ID ) REFERENCES TIPO_EMERGENCIA ( ID ) ;

ALTER TABLE HABITACION ADD CONSTRAINT TIPO_HABITACION_FK FOREIGN KEY ( TIPO_HABITACION_ID ) REFERENCES TIPO_HABITACION ( ID ) ;

ALTER TABLE TIPO_MEDICINA ADD CONSTRAINT TIPO_MEDICINA_MEDICINA_FK FOREIGN KEY ( MEDICINA_ID ) REFERENCES MEDICINA ( ID ) ;

ALTER TABLE TELEFONO_PERSONA ADD CONSTRAINT TIPO_TELEFONO_FK FOREIGN KEY ( TIPO_TELEFONO_ID ) REFERENCES TIPO_TELEFONO ( ID ) ;

ALTER TABLE TRATAMIENTOS ADD CONSTRAINT TRATAMIENTOS_TIPO_FK FOREIGN KEY ( TIPO_TRATAMIENTO_ID ) REFERENCES TIPO_TRATAMIENTO ( ID ) ;

ALTER TABLE TRATAMIENTO_PACIENTE ADD CONSTRAINT TRATAMIENTO_PACIENTE_FK FOREIGN KEY ( PACIENTE_ID ) REFERENCES PACIENTE ( ID ) ;

ALTER TABLE TRATAMIENTO_PACIENTE ADD CONSTRAINT TRATAMIENTO_PACI_FK FOREIGN KEY ( TRATAMIENTOS_ID ) REFERENCES TRATAMIENTOS ( ID ) ;

ALTER TABLE TURNO_AREA ADD CONSTRAINT TURNO_AREA_AREAS_FK FOREIGN KEY ( AREAS_ID ) REFERENCES AREAS ( ID ) ;

ALTER TABLE TURNO_AREA ADD CONSTRAINT TURNO_AREA_EMPLEADO_FK FOREIGN KEY ( EMPLEADO_ID ) REFERENCES EMPLEADO ( ID ) ;

ALTER TABLE TURNO_AREA ADD CONSTRAINT TURNO_AREA_TURNO_FK FOREIGN KEY ( TURNO_ID ) REFERENCES TURNO ( ID ) ;

ALTER TABLE RESPONSABLE_TURNO ADD CONSTRAINT TURNO_FK FOREIGN KEY ( TURNO_ID ) REFERENCES TURNO ( ID ) ;


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            51
-- CREATE INDEX                             0
-- ALTER TABLE                            109
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
