




CREATE TABLE HPTL_TIPO_TRATAMIENTO
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (50)
  )
  LOGGING ;
ALTER TABLE HPTL_TIPO_TRATAMIENTO ADD CONSTRAINT HPTL_TIPO_TRATAMIENTO_PK PRIMARY KEY ( ID ) ;




CREATE TABLE HPTL_ETAPA_TRATAMIENTOS
  (
    ID                   NUMBER NOT NULL ,
    NOETAPA           NUMBER ,
    ETAPA                VARCHAR2 (50) ,
    TRATAMIENTOS_ID NUMBER NOT NULL
  )
  LOGGING ;
ALTER TABLE HPTL_ETAPA_TRATAMIENTOS ADD CONSTRAINT HPTL_ETAPA_TRATAMIENTOS_PK PRIMARY KEY ( ID ) ;





CREATE TABLE HPTL_TRATAMIENTOS
  (
    ID          NUMBER NOT NULL ,
    DESCRIPCION VARCHAR2 (50),
    TIPO_TRATAMIENTO_ID NUMBER NOT NULL
  )
  LOGGING ;
ALTER TABLE HPTL_TRATAMIENTOS ADD CONSTRAINT HPTL_TRATAMIENTOS_PK PRIMARY KEY ( ID ) ;



ALTER TABLE HPTL_ETAPA_TRATAMIENTOS ADD CONSTRAINT HPTL_ETAPA_TRA_HPTL_TRA_FK FOREIGN KEY ( HPTL_TRATAMIENTOS_ID ) REFERENCES HPTL_TRATAMIENTOS ( ID ) NOT DEFERRABLE ;

ALTER TABLE HPTL_TRATAMIENTOS ADD CONSTRAINT HPTL_TRA_PK_HPTL_TIPO_TRA_FK FOREIGN KEY ( TIPO_TRATAMIENTO_ID ) REFERENCES HPTL_TIPO_TRATAMIENTO ( ID ) NOT DEFERRABLE ;


