/* -------------------------------------
	TABLAS EMERGENCIA Y MORGUE
--------------------------------------*/

CREATE TABLE HPTL_SOL_EMERGENCIAS(
	ID INTEGER NOT NULL,
	SOL_OBSERVACIONES VARCHAR2 (2000),
	ADD_FECHA DATE,
	ADD_USER NUMBER(2),
	SOL_ESTADO VARCHAR2 (15),
	OBS_SIGNOSVIT VARCHAR2 (2000),
	ID_ESTADO_EMER NUMBER(1),
	ID_CONSULTA NUMBER(2),
	ID_CAMILLA NUMBER (2),
		CODIGO_PACIENTE INTEGER,
		VERSION NUMERIC(5,0) NOT NULL,
	CONSTRAINT HPTL_SOL_EMERGENCIAS_PK PRIMARY KEY(ID)
);

CREATE TABLE HPTL_EMER_DICTAMEN(
	ID INTEGER NOT NULL,
	TIPO_DICTAMEN CHAR(1),
	OBSERVACIONES_DIC VARCHAR2 (2000),
		SOL_EMERGENCIAS_ID INTEGER,
		VERSION NUMERIC(5,0) NOT NULL,
	CONSTRAINT HPTL_EMER_DICTAMEN_PK PRIMARY KEY(ID),
	CONSTRAINT HPTL_SOL_EMER_PK_HPTL_DIC_FK FOREIGN KEY (SOL_EMERGENCIAS_ID) REFERENCES HPTL_SOL_EMERGENCIAS(ID)
);

CREATE TABLE HPTL_EMER_RECETA(
	ID INTEGER NOT NULL,
	OBSERVACIONES_RECETA VARCHAR2 (2000),
		EMER_DICTAMEN_ID INTEGER,
		VERSION NUMERIC(5,0) NOT NULL,	
	CONSTRAINT HPTL_EMER_RECETA_PK PRIMARY KEY(ID),
	CONSTRAINT HPTL_E_R_PK_HPTL_E_D_FK FOREIGN KEY(EMER_DICTAMEN_ID) REFERENCES HPTL_EMER_DICTAMEN(ID)
);

CREATE TABLE HPTL_EMER_REC_DETALLE(
	ID INTEGER NOT NULL,
	ID_MEDICAMENTO NUMBER (2),
	OBSERVACIONES_DETALLE VARCHAR2(2000),
		EMER_RECETA_ID INTEGER,
		VERSION NUMERIC(5,0) NOT NULL,	
	CONSTRAINT HPTL_EMER_REC_DETALLE_PK PRIMARY KEY(ID),
	CONSTRAINT HPTL_E_R_PK_HPTL_R_DET_FK FOREIGN KEY(EMER_RECETA_ID) REFERENCES HPTL_EMER_RECETA(ID)
);


CREATE TABLE HPTL_CAJA(
	ID INTEGER NOT NULL,
	NIT NUMBER (10),
	NOMBRE	VARCHAR2 (15),
	APELLIDO VARCHAR2 (15),
	DESC_SEGURO NUMBER(15,2),
	DESC_ESPECIAL NUMBER(15,2),
		SOL_EMERGENCIAS_ID INTEGER,
		VERSION NUMERIC(5,0) NOT NULL,	
	CONSTRAINT HPTL_CAJA_PK PRIMARY KEY(ID),
	CONSTRAINT HPTL_SOL_EMER_PK_HPTL_CAJA__FK FOREIGN KEY(SOL_EMERGENCIAS_ID) REFERENCES HPTL_SOL_EMERGENCIAS(ID)
);

CREATE TABLE HPTL_CAJA_DETALLE(
	ID INTEGER NOT NULL,
	NOMBRE_RUBRO VARCHAR2 (15),
	MONTO NUMBER (15,2),
		CAJA_ID INTEGER,
		VERSION NUMERIC(5,0) NOT NULL,	
	CONSTRAINT HPTL_CAJA_DETALLE_PK PRIMARY KEY(ID),
	CONSTRAINT HPTL_CAJA_DET_PK_HPTL_CAJA_FK FOREIGN KEY(CAJA_ID) REFERENCES HPTL_CAJA(ID)
);

CREATE TABLE HPTL_MORGUE(
	ID INTEGER NOT NULL,
	NOMBRE_MUERTO VARCHAR2(15),
	APELLIDO_MUERTO VARCHAR2(15),
	TIPO_SANGRE CHAR(2),
	RESPONSABLE VARCHAR2(30),
	OBSERVACION_FORENCE VARCHAR(2000),
	OBSERVACION_SALIDA VARCHAR(2000),
  ESTADO NUMBER(1),
    SOL_EMERGENCIAS_ID INTEGER,
  	VERSION NUMERIC(5,0) NOT NULL,	
	CONSTRAINT HPTL_MORGUE_PK PRIMARY KEY(ID),
  CONSTRAINT HPTL_MORG_PK_HPTL_SOL_EME_FK FOREIGN KEY (SOL_EMERGENCIAS_ID) REFERENCES HPTL_SOL_EMERGENCIAS(ID)
);
